In [1]:
import pandas as pd
import numpy as np
import xgboost as xgb
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

In [2]:
data = pd.read_csv(r'C:\Users\arjun\Desktop\Temp_files\diabetes.csv')
print(data.shape)
data.head()

(768, 9)


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [3]:
data.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [4]:
#Separating the feature and the Label columns 
x=data.drop(['Outcome'],axis=1)
y=data['Outcome']

In [5]:
x.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [6]:
# as the datapoints differ a lot in magnitude, we'll scale them
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_data = scaler.fit_transform(x)

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(scaled_data,y,test_size=0.3,random_state=45)

In [8]:
# fit model no training data
model = XGBClassifier()
model.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method=None,
              validate_parameters=False, verbosity=None)

In [9]:
# cheking training accuracy
y_pred = model.predict(x_test)
y_pred

array([0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0], dtype=int64)

In [10]:
model.score(x_test,y_test)

0.70995670995671

In [11]:
accuracy = accuracy_score(y_test,y_pred)
accuracy 

0.70995670995671

In [12]:
# Now to increae the accuracy of the model, we'll do hyperparameter tuning using grid search
from sklearn.model_selection import GridSearchCV

In [13]:
param_grid = { 'learning_rate':[1,0.5,0.1,0.01,0.001],
                'max_depth': [3,5,10,20],
            'n_estimators':[10,50,100,200]
 }

In [14]:
grid=GridSearchCV(estimator=model, param_grid=param_grid , cv=3,verbose=3)

In [15]:
grid.fit(x_train,y_train)

Fitting 3 folds for each of 80 candidates, totalling 240 fits
[CV] learning_rate=1, max_depth=3, n_estimators=10 ...................
[CV]  learning_rate=1, max_depth=3, n_estimators=10, score=0.760, total=   0.0s
[CV] learning_rate=1, max_depth=3, n_estimators=10 ...................
[CV]  learning_rate=1, max_depth=3, n_estimators=10, score=0.721, total=   0.0s
[CV] learning_rate=1, max_depth=3, n_estimators=10 ...................
[CV]  learning_rate=1, max_depth=3, n_estimators=10, score=0.799, total=   0.0s
[CV] learning_rate=1, max_depth=3, n_estimators=50 ...................
[CV]  learning_rate=1, max_depth=3, n_estimators=50, score=0.715, total=   0.0s
[CV] learning_rate=1, max_depth=3, n_estimators=50 ...................
[CV]  learning_rate=1, max_depth=3, n_estimators=50, score=0.732, total=   0.0s
[CV] learning_rate=1, max_depth=3, n_estimators=50 ...................
[CV]  learning_rate=1, max_depth=3, n_estimators=50, score=0.771, total=   0.0s
[CV] learning_rate=1, max_depth=

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:    0.0s remaining:    0.0s


[CV]  learning_rate=1, max_depth=3, n_estimators=100, score=0.721, total=   0.1s
[CV] learning_rate=1, max_depth=3, n_estimators=100 ..................
[CV]  learning_rate=1, max_depth=3, n_estimators=100, score=0.732, total=   0.1s
[CV] learning_rate=1, max_depth=3, n_estimators=100 ..................
[CV]  learning_rate=1, max_depth=3, n_estimators=100, score=0.760, total=   0.1s
[CV] learning_rate=1, max_depth=3, n_estimators=200 ..................
[CV]  learning_rate=1, max_depth=3, n_estimators=200, score=0.715, total=   0.1s
[CV] learning_rate=1, max_depth=3, n_estimators=200 ..................
[CV]  learning_rate=1, max_depth=3, n_estimators=200, score=0.721, total=   0.1s
[CV] learning_rate=1, max_depth=3, n_estimators=200 ..................
[CV]  learning_rate=1, max_depth=3, n_estimators=200, score=0.760, total=   0.1s
[CV] learning_rate=1, max_depth=5, n_estimators=10 ...................
[CV]  learning_rate=1, max_depth=5, n_estimators=10, score=0.760, total=   0.0s
[CV] lea

[CV]  learning_rate=0.5, max_depth=5, n_estimators=50, score=0.732, total=   0.0s
[CV] learning_rate=0.5, max_depth=5, n_estimators=50 .................
[CV]  learning_rate=0.5, max_depth=5, n_estimators=50, score=0.737, total=   0.0s
[CV] learning_rate=0.5, max_depth=5, n_estimators=50 .................
[CV]  learning_rate=0.5, max_depth=5, n_estimators=50, score=0.749, total=   0.0s
[CV] learning_rate=0.5, max_depth=5, n_estimators=100 ................
[CV]  learning_rate=0.5, max_depth=5, n_estimators=100, score=0.726, total=   0.1s
[CV] learning_rate=0.5, max_depth=5, n_estimators=100 ................
[CV]  learning_rate=0.5, max_depth=5, n_estimators=100, score=0.726, total=   0.1s
[CV] learning_rate=0.5, max_depth=5, n_estimators=100 ................
[CV]  learning_rate=0.5, max_depth=5, n_estimators=100, score=0.743, total=   0.1s
[CV] learning_rate=0.5, max_depth=5, n_estimators=200 ................
[CV]  learning_rate=0.5, max_depth=5, n_estimators=200, score=0.732, total=   0

[CV]  learning_rate=0.1, max_depth=5, n_estimators=200, score=0.732, total=   0.1s
[CV] learning_rate=0.1, max_depth=5, n_estimators=200 ................
[CV]  learning_rate=0.1, max_depth=5, n_estimators=200, score=0.765, total=   0.1s
[CV] learning_rate=0.1, max_depth=10, n_estimators=10 ................
[CV]  learning_rate=0.1, max_depth=10, n_estimators=10, score=0.754, total=   0.0s
[CV] learning_rate=0.1, max_depth=10, n_estimators=10 ................
[CV]  learning_rate=0.1, max_depth=10, n_estimators=10, score=0.749, total=   0.0s
[CV] learning_rate=0.1, max_depth=10, n_estimators=10 ................
[CV]  learning_rate=0.1, max_depth=10, n_estimators=10, score=0.721, total=   0.0s
[CV] learning_rate=0.1, max_depth=10, n_estimators=50 ................
[CV]  learning_rate=0.1, max_depth=10, n_estimators=50, score=0.737, total=   0.1s
[CV] learning_rate=0.1, max_depth=10, n_estimators=50 ................
[CV]  learning_rate=0.1, max_depth=10, n_estimators=50, score=0.765, total= 

[CV]  learning_rate=0.01, max_depth=10, n_estimators=50, score=0.709, total=   0.1s
[CV] learning_rate=0.01, max_depth=10, n_estimators=100 ..............
[CV]  learning_rate=0.01, max_depth=10, n_estimators=100, score=0.765, total=   0.1s
[CV] learning_rate=0.01, max_depth=10, n_estimators=100 ..............
[CV]  learning_rate=0.01, max_depth=10, n_estimators=100, score=0.760, total=   0.1s
[CV] learning_rate=0.01, max_depth=10, n_estimators=100 ..............
[CV]  learning_rate=0.01, max_depth=10, n_estimators=100, score=0.726, total=   0.1s
[CV] learning_rate=0.01, max_depth=10, n_estimators=200 ..............
[CV]  learning_rate=0.01, max_depth=10, n_estimators=200, score=0.754, total=   0.2s
[CV] learning_rate=0.01, max_depth=10, n_estimators=200 ..............
[CV]  learning_rate=0.01, max_depth=10, n_estimators=200, score=0.771, total=   0.2s
[CV] learning_rate=0.01, max_depth=10, n_estimators=200 ..............
[CV]  learning_rate=0.01, max_depth=10, n_estimators=200, score=0

[CV]  learning_rate=0.001, max_depth=10, n_estimators=200, score=0.704, total=   0.2s
[CV] learning_rate=0.001, max_depth=10, n_estimators=200 .............
[CV]  learning_rate=0.001, max_depth=10, n_estimators=200, score=0.704, total=   0.2s
[CV] learning_rate=0.001, max_depth=20, n_estimators=10 ..............
[CV]  learning_rate=0.001, max_depth=20, n_estimators=10, score=0.721, total=   0.0s
[CV] learning_rate=0.001, max_depth=20, n_estimators=10 ..............
[CV]  learning_rate=0.001, max_depth=20, n_estimators=10, score=0.693, total=   0.0s
[CV] learning_rate=0.001, max_depth=20, n_estimators=10 ..............
[CV]  learning_rate=0.001, max_depth=20, n_estimators=10, score=0.709, total=   0.0s
[CV] learning_rate=0.001, max_depth=20, n_estimators=50 ..............
[CV]  learning_rate=0.001, max_depth=20, n_estimators=50, score=0.715, total=   0.1s
[CV] learning_rate=0.001, max_depth=20, n_estimators=50 ..............
[CV]  learning_rate=0.001, max_depth=20, n_estimators=50, scor

[Parallel(n_jobs=1)]: Done 240 out of 240 | elapsed:   17.1s finished


GridSearchCV(cv=3, error_score=nan,
             estimator=XGBClassifier(base_score=0.5, booster=None,
                                     colsample_bylevel=1, colsample_bynode=1,
                                     colsample_bytree=1, gamma=0, gpu_id=-1,
                                     importance_type='gain',
                                     interaction_constraints=None,
                                     learning_rate=0.300000012,
                                     max_delta_step=0, max_depth=6,
                                     min_child_weight=1, missing=nan,
                                     monotone_constraints=None,
                                     n_estimators=100, n_jobs=...
                                     objective='binary:logistic',
                                     random_state=0, reg_alpha=0, reg_lambda=1,
                                     scale_pos_weight=1, subsample=1,
                                     tree_method=None,
           

In [16]:
grid.best_params_

{'learning_rate': 0.5, 'max_depth': 20, 'n_estimators': 10}

In [17]:
model1=XGBClassifier(learning_rate = 0.5, max_depth= 20, n_estimators = 10)
model1.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster=None, colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints=None,
              learning_rate=0.5, max_delta_step=0, max_depth=20,
              min_child_weight=1, missing=nan, monotone_constraints=None,
              n_estimators=10, n_jobs=0, num_parallel_tree=1,
              objective='binary:logistic', random_state=0, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, subsample=1, tree_method=None,
              validate_parameters=False, verbosity=None)

In [42]:
print(len(y_test))

231


In [43]:
y_pred1=model1.predict(x_test)
print(len(y_pred1))
y_pred1

231


array([0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0], dtype=int64)

In [44]:
accuracy_1=accuracy_score(y_test,y_pred1)
accuracy_1

0.7272727272727273

In [45]:
model1.score(x_test,y_test)

0.7272727272727273

In [47]:
i=scaler.fit_transform([[10,115,0,0,0,35.3,0.134,29]])
y_pred11=model1.predict(i)
y_pred11

array([0], dtype=int64)

In [48]:
j=scaler.fit_transform([[10,125,70,26,115,31.1,0.205,41]])
y_pred12=model1.predict(j)
y_pred12

array([0], dtype=int64)

In [60]:
j=scaler.fit_transform([[6,148,72,35,80,33.6,0.627,50]])
y_pred13=model1.predict(j)
y_pred13

array([0], dtype=int64)

In [50]:
from sklearn.metrics import confusion_matrix,classification_report

In [51]:
confu=confusion_matrix(y_test,y_pred1)
confu

array([[124,  30],
       [ 33,  44]], dtype=int64)

In [54]:
classi_report=classification_report(y_test,y_pred1)
print(classi_report)

              precision    recall  f1-score   support

           0       0.79      0.81      0.80       154
           1       0.59      0.57      0.58        77

    accuracy                           0.73       231
   macro avg       0.69      0.69      0.69       231
weighted avg       0.72      0.73      0.73       231



In [58]:
# As we have increased the accuracy of the model, we'll save this model
import pickle
filname_scaler = 'XGBoost_scaler_model.pickle'
pickle.dump(scaler,open(filname_scaler, 'wb'))

scaler_model = pickle.load(open(filname_scaler, 'rb'))